### ISSUE TITLE
Problemi con la AuthnRequest durante la chiamata "Check Strict"

### ISSUE THREAD

**Issue by fatnik** [italia/spid-spring#20]
Sto provando a far funzionare ma durante la fase di test (sto usando: **spid-saml-check**) quando faccio la chiamata "Check Strict" mi viene restituito sempre un blocco con numero 28 **AuthnRequest Signature validation failed**.

Sotto riporto una foto di quel blocco.

![image](https://user-images.githubusercontent.com/19865852/134512911-829c2956-fc6e-4d6f-9b97-d23a7206d314.png)

Se puo essere utile ho allegato anche XML del "AuthnRequest"
[AuthnRequest.txt](https://github.com/italia/spid-spring/files/7217867/AuthnRequest.txt)

Spero che mi potete aiutare.
Grazie

**Comment by peppelinux** [comment]
allega anche il metadata eventualmente,

quello che vedi è il messaggio di signature validation failure di xmlsec1

**Comment by fatnik** [comment]
In allegato trovi il metadata.
Grazie in anticipo
[metadata.txt](https://github.com/italia/spid-spring/files/7218329/metadata.txt)

**Comment by peppelinux** [comment]
il certificato x509 contenuto all'interno della authn request non è contenuto nel metadata, probabilmente firmi con una chiave privata diversa

**Comment by fatnik** [comment]
Grazie mille della risposta
