### ISSUE TITLE
Zero test run in Travis CI master build

### ISSUE THREAD

**Issue by gvespucci** [italia/spid-spring#25]
Dando una occhiata al log della ultima [build di master](https://travis-ci.org/github/italia/spid-spring/builds/771660171) di Travis CI, sembra come se non esegua in realtà nessuna test del modulo `spid-spring-integration`.
```
-------------------------------------------------------

 T E S T S

-------------------------------------------------------

Running it.italia.developers.spid.integration.service.test.SPIDIntegrationServiceTest

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec

Running it.italia.developers.spid.integration.util.SPIDIntegrationUtilTest

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```
IMHO credo manchi la dipendenza esplicita dal `maven-surefire-plugin` nel main `pom.xml`.

Sono io che mi sto perdendo qualcosa?
Grazie

**Comment by peppelinux** [comment]
Ciao @gvespucci 
se possibile consiglierei vivamente di abbandonare travis e migrare a gh actions

**Comment by gvespucci** [comment]
Ciao @peppelinux, nulla in contrario. In realtà questa cosa dei 0 test credo abbia rivelato un problema di configurazione di Maven. Ho aggiunto la configurazione di Surefire, come dicevo su, e i test vengono invocati durante la build. 
Ma ora abbiamo 2 fallimenti dovute a 2 NPE. 🤔 
Siccome ho appena conosciuto il progetto, non so bene chi siano i maintainer e di come continuare la discussione. Cosa mi consigli? Grazie

**Comment by peppelinux** [comment]
Sentiti libero di fare PR, io vedrò la CI funzionare e lo uniamo

raggiungici su slack developers italia, sul canale spid-spring, se vuoi conoscere i developers che nel tempo hanno contribuito

**Comment by gvespucci** [comment]
Pull request: #28.
